version: "3.8"
services:
  m2m:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: m2m:django
    container_name: django_con
    command: python manage.py runserver 0.0.0.0:8000