# Generated by Django 3.2.7 on 2021-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_movieactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='cinema.Actor'),
        ),
        migrations.DeleteModel(
            name='MovieActor',
        ),
    ]
